//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  tudastar: Tudastar;
  tudastarConnection: TudastarConnection;
  siteConfig: SiteConfig;
  siteConfigConnection: SiteConfigConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  pricing: Pricing;
  pricingConnection: PricingConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTudastarArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTudastarConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TudastarFilter>;
};


export type QuerySiteConfigArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConfigConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteConfigFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryPricingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPricingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingFilter>;
};

export type DocumentFilter = {
  tudastar?: InputMaybe<TudastarFilter>;
  siteConfig?: InputMaybe<SiteConfigFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  pricing?: InputMaybe<PricingFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Tudastar | SiteConfig | Homepage | Pricing | Folder;

export type Tudastar = Node & Document & {
  __typename?: 'Tudastar';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  pubDate: Scalars['String']['output'];
  updatedDate?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TudastarFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  updatedDate?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TudastarConnectionEdges = {
  __typename?: 'TudastarConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tudastar>;
};

export type TudastarConnection = Connection & {
  __typename?: 'TudastarConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TudastarConnectionEdges>>>;
};

export type SiteConfigStats = {
  __typename?: 'SiteConfigStats';
  references?: Maybe<Scalars['String']['output']>;
  experience?: Maybe<Scalars['String']['output']>;
  warranty?: Maybe<Scalars['String']['output']>;
  districts?: Maybe<Scalars['String']['output']>;
};

export type SiteConfig = Node & Document & {
  __typename?: 'SiteConfig';
  name?: Maybe<Scalars['String']['output']>;
  legalName?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  phoneTel?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  owner?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  facebookUrl?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<SiteConfigStats>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteConfigStatsFilter = {
  references?: InputMaybe<StringFilter>;
  experience?: InputMaybe<StringFilter>;
  warranty?: InputMaybe<StringFilter>;
  districts?: InputMaybe<StringFilter>;
};

export type SiteConfigFilter = {
  name?: InputMaybe<StringFilter>;
  legalName?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  phoneTel?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  owner?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  facebookUrl?: InputMaybe<StringFilter>;
  stats?: InputMaybe<SiteConfigStatsFilter>;
};

export type SiteConfigConnectionEdges = {
  __typename?: 'SiteConfigConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteConfig>;
};

export type SiteConfigConnection = Connection & {
  __typename?: 'SiteConfigConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConfigConnectionEdges>>>;
};

export type HomepageServices = {
  __typename?: 'HomepageServices';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['Boolean']['output']>;
};

export type HomepageProcessSteps = {
  __typename?: 'HomepageProcessSteps';
  step?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type HomepageBrands = {
  __typename?: 'HomepageBrands';
  name?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type HomepageFaqs = {
  __typename?: 'HomepageFaqs';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroBadgeText?: Maybe<Scalars['String']['output']>;
  heroCtaPrimary?: Maybe<Scalars['String']['output']>;
  heroCtaSecondary?: Maybe<Scalars['String']['output']>;
  heroImageUrl?: Maybe<Scalars['String']['output']>;
  heroImageAlt?: Maybe<Scalars['String']['output']>;
  servicesSectionTitle?: Maybe<Scalars['String']['output']>;
  servicesSectionSubtitle?: Maybe<Scalars['String']['output']>;
  services?: Maybe<Array<Maybe<HomepageServices>>>;
  processSteps?: Maybe<Array<Maybe<HomepageProcessSteps>>>;
  brands?: Maybe<Array<Maybe<HomepageBrands>>>;
  faqs?: Maybe<Array<Maybe<HomepageFaqs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomepageServicesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<BooleanFilter>;
};

export type HomepageProcessStepsFilter = {
  step?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type HomepageBrandsFilter = {
  name?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomepageFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type HomepageFilter = {
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  heroBadgeText?: InputMaybe<StringFilter>;
  heroCtaPrimary?: InputMaybe<StringFilter>;
  heroCtaSecondary?: InputMaybe<StringFilter>;
  heroImageUrl?: InputMaybe<StringFilter>;
  heroImageAlt?: InputMaybe<StringFilter>;
  servicesSectionTitle?: InputMaybe<StringFilter>;
  servicesSectionSubtitle?: InputMaybe<StringFilter>;
  services?: InputMaybe<HomepageServicesFilter>;
  processSteps?: InputMaybe<HomepageProcessStepsFilter>;
  brands?: InputMaybe<HomepageBrandsFilter>;
  faqs?: InputMaybe<HomepageFaqsFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type PricingInstallPrices = {
  __typename?: 'PricingInstallPrices';
  service?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  note?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['Boolean']['output']>;
};

export type PricingDevicePrices = {
  __typename?: 'PricingDevicePrices';
  service?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['Boolean']['output']>;
};

export type PricingServicePrices = {
  __typename?: 'PricingServicePrices';
  service?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['Boolean']['output']>;
};

export type PricingFaqs = {
  __typename?: 'PricingFaqs';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type Pricing = Node & Document & {
  __typename?: 'Pricing';
  installPrices?: Maybe<Array<Maybe<PricingInstallPrices>>>;
  devicePrices?: Maybe<Array<Maybe<PricingDevicePrices>>>;
  servicePrices?: Maybe<Array<Maybe<PricingServicePrices>>>;
  faqs?: Maybe<Array<Maybe<PricingFaqs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PricingInstallPricesFilter = {
  service?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  note?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<BooleanFilter>;
};

export type PricingDevicePricesFilter = {
  service?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<BooleanFilter>;
};

export type PricingServicePricesFilter = {
  service?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<BooleanFilter>;
};

export type PricingFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type PricingFilter = {
  installPrices?: InputMaybe<PricingInstallPricesFilter>;
  devicePrices?: InputMaybe<PricingDevicePricesFilter>;
  servicePrices?: InputMaybe<PricingServicePricesFilter>;
  faqs?: InputMaybe<PricingFaqsFilter>;
};

export type PricingConnectionEdges = {
  __typename?: 'PricingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pricing>;
};

export type PricingConnection = Connection & {
  __typename?: 'PricingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PricingConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateTudastar: Tudastar;
  createTudastar: Tudastar;
  updateSiteConfig: SiteConfig;
  createSiteConfig: SiteConfig;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updatePricing: Pricing;
  createPricing: Pricing;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateTudastarArgs = {
  relativePath: Scalars['String']['input'];
  params: TudastarMutation;
};


export type MutationCreateTudastarArgs = {
  relativePath: Scalars['String']['input'];
  params: TudastarMutation;
};


export type MutationUpdateSiteConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteConfigMutation;
};


export type MutationCreateSiteConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteConfigMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdatePricingArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingMutation;
};


export type MutationCreatePricingArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingMutation;
};

export type DocumentUpdateMutation = {
  tudastar?: InputMaybe<TudastarMutation>;
  siteConfig?: InputMaybe<SiteConfigMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  pricing?: InputMaybe<PricingMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  tudastar?: InputMaybe<TudastarMutation>;
  siteConfig?: InputMaybe<SiteConfigMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  pricing?: InputMaybe<PricingMutation>;
};

export type TudastarMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  updatedDate?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SiteConfigStatsMutation = {
  references?: InputMaybe<Scalars['String']['input']>;
  experience?: InputMaybe<Scalars['String']['input']>;
  warranty?: InputMaybe<Scalars['String']['input']>;
  districts?: InputMaybe<Scalars['String']['input']>;
};

export type SiteConfigMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  legalName?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  phoneTel?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  owner?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  facebookUrl?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<SiteConfigStatsMutation>;
};

export type HomepageServicesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomepageProcessStepsMutation = {
  step?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageBrandsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroBadgeText?: InputMaybe<Scalars['String']['input']>;
  heroCtaPrimary?: InputMaybe<Scalars['String']['input']>;
  heroCtaSecondary?: InputMaybe<Scalars['String']['input']>;
  heroImageUrl?: InputMaybe<Scalars['String']['input']>;
  heroImageAlt?: InputMaybe<Scalars['String']['input']>;
  servicesSectionTitle?: InputMaybe<Scalars['String']['input']>;
  servicesSectionSubtitle?: InputMaybe<Scalars['String']['input']>;
  services?: InputMaybe<Array<InputMaybe<HomepageServicesMutation>>>;
  processSteps?: InputMaybe<Array<InputMaybe<HomepageProcessStepsMutation>>>;
  brands?: InputMaybe<Array<InputMaybe<HomepageBrandsMutation>>>;
  faqs?: InputMaybe<Array<InputMaybe<HomepageFaqsMutation>>>;
};

export type PricingInstallPricesMutation = {
  service?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  note?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PricingDevicePricesMutation = {
  service?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PricingServicePricesMutation = {
  service?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PricingFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type PricingMutation = {
  installPrices?: InputMaybe<Array<InputMaybe<PricingInstallPricesMutation>>>;
  devicePrices?: InputMaybe<Array<InputMaybe<PricingDevicePricesMutation>>>;
  servicePrices?: InputMaybe<Array<InputMaybe<PricingServicePricesMutation>>>;
  faqs?: InputMaybe<Array<InputMaybe<PricingFaqsMutation>>>;
};

export type TudastarPartsFragment = { __typename: 'Tudastar', title: string, description: string, pubDate: string, updatedDate?: string | null, author?: string | null, tags?: Array<string | null> | null, image?: string | null, imageAlt?: string | null, keywords?: Array<string | null> | null, body?: any | null };

export type SiteConfigPartsFragment = { __typename: 'SiteConfig', name?: string | null, legalName?: string | null, tagline?: string | null, phone?: string | null, phoneTel?: string | null, email?: string | null, owner?: string | null, description?: string | null, facebookUrl?: string | null, stats?: { __typename: 'SiteConfigStats', references?: string | null, experience?: string | null, warranty?: string | null, districts?: string | null } | null };

export type HomepagePartsFragment = { __typename: 'Homepage', heroTitle?: string | null, heroSubtitle?: string | null, heroBadgeText?: string | null, heroCtaPrimary?: string | null, heroCtaSecondary?: string | null, heroImageUrl?: string | null, heroImageAlt?: string | null, servicesSectionTitle?: string | null, servicesSectionSubtitle?: string | null, services?: Array<{ __typename: 'HomepageServices', title?: string | null, description?: string | null, href?: string | null, icon?: string | null, image?: string | null, imageAlt?: string | null, highlight?: boolean | null } | null> | null, processSteps?: Array<{ __typename: 'HomepageProcessSteps', step?: string | null, title?: string | null, desc?: string | null } | null> | null, brands?: Array<{ __typename: 'HomepageBrands', name?: string | null, desc?: string | null, href?: string | null } | null> | null, faqs?: Array<{ __typename: 'HomepageFaqs', question?: string | null, answer?: string | null } | null> | null };

export type PricingPartsFragment = { __typename: 'Pricing', installPrices?: Array<{ __typename: 'PricingInstallPrices', service?: string | null, description?: string | null, price?: string | null, note?: string | null, highlight?: boolean | null } | null> | null, devicePrices?: Array<{ __typename: 'PricingDevicePrices', service?: string | null, description?: string | null, price?: string | null, highlight?: boolean | null } | null> | null, servicePrices?: Array<{ __typename: 'PricingServicePrices', service?: string | null, description?: string | null, price?: string | null, highlight?: boolean | null } | null> | null, faqs?: Array<{ __typename: 'PricingFaqs', question?: string | null, answer?: string | null } | null> | null };

export type TudastarQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TudastarQuery = { __typename?: 'Query', tudastar: { __typename: 'Tudastar', id: string, title: string, description: string, pubDate: string, updatedDate?: string | null, author?: string | null, tags?: Array<string | null> | null, image?: string | null, imageAlt?: string | null, keywords?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TudastarConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TudastarFilter>;
}>;


export type TudastarConnectionQuery = { __typename?: 'Query', tudastarConnection: { __typename?: 'TudastarConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TudastarConnectionEdges', cursor: string, node?: { __typename: 'Tudastar', id: string, title: string, description: string, pubDate: string, updatedDate?: string | null, author?: string | null, tags?: Array<string | null> | null, image?: string | null, imageAlt?: string | null, keywords?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiteConfigQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteConfigQuery = { __typename?: 'Query', siteConfig: { __typename: 'SiteConfig', id: string, name?: string | null, legalName?: string | null, tagline?: string | null, phone?: string | null, phoneTel?: string | null, email?: string | null, owner?: string | null, description?: string | null, facebookUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: { __typename: 'SiteConfigStats', references?: string | null, experience?: string | null, warranty?: string | null, districts?: string | null } | null } };

export type SiteConfigConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteConfigFilter>;
}>;


export type SiteConfigConnectionQuery = { __typename?: 'Query', siteConfigConnection: { __typename?: 'SiteConfigConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConfigConnectionEdges', cursor: string, node?: { __typename: 'SiteConfig', id: string, name?: string | null, legalName?: string | null, tagline?: string | null, phone?: string | null, phoneTel?: string | null, email?: string | null, owner?: string | null, description?: string | null, facebookUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: { __typename: 'SiteConfigStats', references?: string | null, experience?: string | null, warranty?: string | null, districts?: string | null } | null } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, heroTitle?: string | null, heroSubtitle?: string | null, heroBadgeText?: string | null, heroCtaPrimary?: string | null, heroCtaSecondary?: string | null, heroImageUrl?: string | null, heroImageAlt?: string | null, servicesSectionTitle?: string | null, servicesSectionSubtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'HomepageServices', title?: string | null, description?: string | null, href?: string | null, icon?: string | null, image?: string | null, imageAlt?: string | null, highlight?: boolean | null } | null> | null, processSteps?: Array<{ __typename: 'HomepageProcessSteps', step?: string | null, title?: string | null, desc?: string | null } | null> | null, brands?: Array<{ __typename: 'HomepageBrands', name?: string | null, desc?: string | null, href?: string | null } | null> | null, faqs?: Array<{ __typename: 'HomepageFaqs', question?: string | null, answer?: string | null } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, heroTitle?: string | null, heroSubtitle?: string | null, heroBadgeText?: string | null, heroCtaPrimary?: string | null, heroCtaSecondary?: string | null, heroImageUrl?: string | null, heroImageAlt?: string | null, servicesSectionTitle?: string | null, servicesSectionSubtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'HomepageServices', title?: string | null, description?: string | null, href?: string | null, icon?: string | null, image?: string | null, imageAlt?: string | null, highlight?: boolean | null } | null> | null, processSteps?: Array<{ __typename: 'HomepageProcessSteps', step?: string | null, title?: string | null, desc?: string | null } | null> | null, brands?: Array<{ __typename: 'HomepageBrands', name?: string | null, desc?: string | null, href?: string | null } | null> | null, faqs?: Array<{ __typename: 'HomepageFaqs', question?: string | null, answer?: string | null } | null> | null } | null } | null> | null } };

export type PricingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PricingQuery = { __typename?: 'Query', pricing: { __typename: 'Pricing', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, installPrices?: Array<{ __typename: 'PricingInstallPrices', service?: string | null, description?: string | null, price?: string | null, note?: string | null, highlight?: boolean | null } | null> | null, devicePrices?: Array<{ __typename: 'PricingDevicePrices', service?: string | null, description?: string | null, price?: string | null, highlight?: boolean | null } | null> | null, servicePrices?: Array<{ __typename: 'PricingServicePrices', service?: string | null, description?: string | null, price?: string | null, highlight?: boolean | null } | null> | null, faqs?: Array<{ __typename: 'PricingFaqs', question?: string | null, answer?: string | null } | null> | null } };

export type PricingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingFilter>;
}>;


export type PricingConnectionQuery = { __typename?: 'Query', pricingConnection: { __typename?: 'PricingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PricingConnectionEdges', cursor: string, node?: { __typename: 'Pricing', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, installPrices?: Array<{ __typename: 'PricingInstallPrices', service?: string | null, description?: string | null, price?: string | null, note?: string | null, highlight?: boolean | null } | null> | null, devicePrices?: Array<{ __typename: 'PricingDevicePrices', service?: string | null, description?: string | null, price?: string | null, highlight?: boolean | null } | null> | null, servicePrices?: Array<{ __typename: 'PricingServicePrices', service?: string | null, description?: string | null, price?: string | null, highlight?: boolean | null } | null> | null, faqs?: Array<{ __typename: 'PricingFaqs', question?: string | null, answer?: string | null } | null> | null } | null } | null> | null } };

export const TudastarPartsFragmentDoc = gql`
    fragment TudastarParts on Tudastar {
  __typename
  title
  description
  pubDate
  updatedDate
  author
  tags
  image
  imageAlt
  keywords
  body
}
    `;
export const SiteConfigPartsFragmentDoc = gql`
    fragment SiteConfigParts on SiteConfig {
  __typename
  name
  legalName
  tagline
  phone
  phoneTel
  email
  owner
  description
  facebookUrl
  stats {
    __typename
    references
    experience
    warranty
    districts
  }
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  heroTitle
  heroSubtitle
  heroBadgeText
  heroCtaPrimary
  heroCtaSecondary
  heroImageUrl
  heroImageAlt
  servicesSectionTitle
  servicesSectionSubtitle
  services {
    __typename
    title
    description
    href
    icon
    image
    imageAlt
    highlight
  }
  processSteps {
    __typename
    step
    title
    desc
  }
  brands {
    __typename
    name
    desc
    href
  }
  faqs {
    __typename
    question
    answer
  }
}
    `;
export const PricingPartsFragmentDoc = gql`
    fragment PricingParts on Pricing {
  __typename
  installPrices {
    __typename
    service
    description
    price
    note
    highlight
  }
  devicePrices {
    __typename
    service
    description
    price
    highlight
  }
  servicePrices {
    __typename
    service
    description
    price
    highlight
  }
  faqs {
    __typename
    question
    answer
  }
}
    `;
export const TudastarDocument = gql`
    query tudastar($relativePath: String!) {
  tudastar(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TudastarParts
  }
}
    ${TudastarPartsFragmentDoc}`;
export const TudastarConnectionDocument = gql`
    query tudastarConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TudastarFilter) {
  tudastarConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TudastarParts
      }
    }
  }
}
    ${TudastarPartsFragmentDoc}`;
export const SiteConfigDocument = gql`
    query siteConfig($relativePath: String!) {
  siteConfig(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteConfigParts
  }
}
    ${SiteConfigPartsFragmentDoc}`;
export const SiteConfigConnectionDocument = gql`
    query siteConfigConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteConfigFilter) {
  siteConfigConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteConfigParts
      }
    }
  }
}
    ${SiteConfigPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const PricingDocument = gql`
    query pricing($relativePath: String!) {
  pricing(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PricingParts
  }
}
    ${PricingPartsFragmentDoc}`;
export const PricingConnectionDocument = gql`
    query pricingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PricingFilter) {
  pricingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PricingParts
      }
    }
  }
}
    ${PricingPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      tudastar(variables: TudastarQueryVariables, options?: C): Promise<{data: TudastarQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TudastarQueryVariables, query: string}> {
        return requester<{data: TudastarQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TudastarQueryVariables, query: string}, TudastarQueryVariables>(TudastarDocument, variables, options);
      },
    tudastarConnection(variables?: TudastarConnectionQueryVariables, options?: C): Promise<{data: TudastarConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TudastarConnectionQueryVariables, query: string}> {
        return requester<{data: TudastarConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TudastarConnectionQueryVariables, query: string}, TudastarConnectionQueryVariables>(TudastarConnectionDocument, variables, options);
      },
    siteConfig(variables: SiteConfigQueryVariables, options?: C): Promise<{data: SiteConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConfigQueryVariables, query: string}> {
        return requester<{data: SiteConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConfigQueryVariables, query: string}, SiteConfigQueryVariables>(SiteConfigDocument, variables, options);
      },
    siteConfigConnection(variables?: SiteConfigConnectionQueryVariables, options?: C): Promise<{data: SiteConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConfigConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConfigConnectionQueryVariables, query: string}, SiteConfigConnectionQueryVariables>(SiteConfigConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    pricing(variables: PricingQueryVariables, options?: C): Promise<{data: PricingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingQueryVariables, query: string}> {
        return requester<{data: PricingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingQueryVariables, query: string}, PricingQueryVariables>(PricingDocument, variables, options);
      },
    pricingConnection(variables?: PricingConnectionQueryVariables, options?: C): Promise<{data: PricingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingConnectionQueryVariables, query: string}> {
        return requester<{data: PricingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingConnectionQueryVariables, query: string}, PricingConnectionQueryVariables>(PricingConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/9024a221-2722-48cf-b4bf-e7f26a2bc930/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  